<?php

/**
 * ProcessWire Fieldtype Image Extra
 *
 * See README.md for usage instructions.
 *
 * ProcessWire 2.x
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * @author Tabea David <td@kf-interactive.com>
 * @version 1.0.1
 * @copyright Copyright (c) 2014 KF Interactive, www.kf-interactive.com, <info@kf-interactive.com>
 * @see https://github.com/justonestep/processwire-fieldtypeimageextra
 * @see http://www.processwire.com
 * @see http://www.ryancramer.com
 *
 */

/**
 * Class InputfieldImageExtra
 */
class InputfieldImageExtra extends InputfieldImage implements ConfigurableModule {

  /**
   * @field array Default config values
   *
   */
  protected static $defaults = array(
    'orientationField' => true,
    'orientationValues' => 'left,right',
    'titleField' => true,
    'descriptionField' => true,
    'linkField' => true,
    'otherField' => ''
  );


  /**
   * Retrieves module meta data
   *
   * Implementation of the Module interface
   *
   * @return array
   * @see http://processwire.com/apigen/class-Module.html
   */
  public static function getModuleInfo() {
    return array(
      'title' => 'Images Extra Inputfield',
      'version' => 101,
      'summary' => 'One or more image uploads (sortable) with extra fields',
      'href' => 'https://github.com/justonestep/processwire-fieldtypeimageextra',
    );
  }

  /**
   * Retrieves the list of config input fields
   *
   * Implementation of the ConfigurableModule interface
   *
   * @param array $data The config data
   * @return InputfieldWrapper
   * @see http://processwire.com/apigen/class-ConfigurableModule.html
   */
  public static function getModuleConfigInputfields(array $data) {
    $fields = new InputfieldWrapper();
    $modules = wire('modules');

    // default config values
    $data = array_merge(self::$defaults, $data);

    $settings = array(
      'orientationField' => array(
        'type' => 'InputfieldCheckbox',
        'description' => 'Enable Image Orientation Select Field' . PHP_EOL . '(activate the checkbox to enable field `orientation`)',
        'checked' => empty($data['orientationField']) ? '' : 'checked',
        'columnWidth' => 25
      ),
      'orientationValues' => array(
        'type' => 'InputfieldText',
        'description' => 'Values for Image Orientation Select Field' . PHP_EOL . '(comma-separated list)',
        'size' => 45,
        'placeholder' => 'left,right',
        'columnWidth' => 25
      ),
      'titleField' => array(
        'type' => 'InputfieldCheckbox',
        'description' => 'Enable Title Input Field' . PHP_EOL . '(activate the checkbox to enable field `title`)',
        'checked' => empty($data['titleField']) ? '' : 'checked',
        'columnWidth' => 25
      ),
      'descriptionField' => array(
        'type' => 'InputfieldCheckbox',
        'description' => 'Enable Description Text Field' . PHP_EOL . '(activate the checkbox to enable field `description`)',
        'checked' => empty($data['descriptionField']) ? '' : 'checked',
        'columnWidth' => 25
      ),
      'linkField' => array(
        'type' => 'InputfieldCheckbox',
        'description' => 'Enable Choose-Link Field' . PHP_EOL . '(activate the checkbox to enable field `link`)',
        'checked' => empty($data['linkField']) ? '' : 'checked',
        'columnWidth' => 25
      ),
      'otherField' => array(
        'type' => 'InputfieldText',
        'description' => 'Add other fields as simple inputs' . PHP_EOL . '(comma-separated list)',
        'size' => 80,
        'placeholder' => '',
        'columnWidth' => 25
      ),
    );

    // assign fields
    foreach ($settings as $name => $s) {
      $field = $modules->get($s['type']);
      $field->name = $name;
      $field->label = $name;
      $field->value = $data[$name];

      foreach ($s as $key => $val) {
        if ($key != 'type') {
          $field->{$key} = $val;
        }
      }

      $fields->append($field);
    }

    return $fields;
  }

  /**
   * customfields array , that we use to hold our submitted customfields
   *
   */
  protected $customFields = array();

  /**
   * init
   *
   */
  public function init() {
    parent::init();
  }

  /**
   * addCustomField - add custom field
   *
   * @param string $type
   * @param string $name
   * @param string $label
   */
  public function addCustomField($type, $name, $label) {
    $this->customFields[] = array(
      'name' => $name,
      'type' => $type,
      'label' => $label
    );
  }

  /**
   * render - add respectively css and js
   *
   */
  public function ___render() {
    foreach (array('InputfieldFile', 'InputfieldImage') as $item) {
      foreach (array('scripts' => '.js', 'styles' => '.css') as $type => $fileExtension) {
        $this->config->{$type}->add($this->config->urls->{$item} . $item . $fileExtension);
      }
    }
 
    foreach (array('scripts' => '.js', 'styles' => '.css') as $type => $fileExtension) {
      $this->config->{$type}->add($this->config->urls->InputfieldImageExtra . 'ImageExtraLanguage' . $fileExtension);
    }

    return parent::___render();
  }

  /**
   * renderItemDescriptionField - build html structure for the backend
   *
   * @param Pagefile $pagefile
   * @param string $id
   * @param int $n
   */
  protected function renderItemDescriptionField(Pagefile $pagefile, $id, $n) {
    $out = array();
    $languageIDs = $this->getLanguages();

    foreach ($this->customFields as $field) {
      $for = $field['name'] . '_' . $id;
      $label = ucfirst($field['label']);
      $name = $field['name'];

      // it is a language field?
      if (preg_match('/([0-9])\w+/', $name)) {
        $labelSplit = preg_replace('/([0-9]\w+)/', ',$1', $label);
        $labelSplitted = explode(',', $labelSplit);
        $label = $labelSplitted[0] . ' ' . $languageIDs[$labelSplitted[1]];
        $basicField = preg_replace('/([0-9]\w+)/', '', $name);
      } else {
        $basicField = $name;
      }

      // assign html output depending on field
      switch ($name) {
        // orientation field, select
        case 'orientation':
          $out[$basicField] = "<label for='$for' class='infield'>$label</label>";
          $out[$basicField] .= "<select name='$for' size='1'>";

          foreach (explode(',', $this->data['orientationValues']) as $type) {
            $selected = $pagefile->{$name} === $type ? 'selected' : '';
            $out[$basicField] .= "<option value='$type' $selected>$type</option>";
          }

          $out[$basicField] .= "</select>";
        break;

        // title field, input
        case 'title':
          $value = htmlspecialchars($pagefile->{$name}, ENT_QUOTES, "UTF-8");
          $class = 'InputfieldFileDescription input-imageextra input-imageextra infield';
          $out[$basicField] = "<label for='$for' data-group='{$basicField}' class='{$class}'>$label";
          $out[$basicField] .= "<input type='text' name='$for' id='$for' value='$value' /></label>";
        break;

        // title fields multi-language, input
        case (preg_match('/title([0-9])\w+/', $name) ? true : false):
          $value = htmlspecialchars($pagefile->{$name}, ENT_QUOTES, "UTF-8");
          $class = 'InputfieldFileDescription input-imageextra__language infield';
          $out[$basicField] .= "<label for='$for' data-group='{$basicField}' class='{$class}'>$label";
          $out[$basicField] .= "<input type='text' name='$for' id='$for' value='$value' /></label>";
        break;

        // description field, textarea
        case 'description':
          $class = 'InputfieldFileDescription input-imageextra infield';
          $value = htmlspecialchars($pagefile->{$name}, ENT_QUOTES, "UTF-8");
          $out[$basicField] = "<label for='$for' data-group='{$basicField}' class='{$class}'>$label";
          $out[$basicField] .= "<textarea id='$for' name='$for' rows='3'>$value</textarea></label>";
        break;

        // descriptions field multi-language, textarea
        case (preg_match('/description.*/', $name) ? true : false):
          $class = 'InputfieldFileDescription input-imageextra__language infield';
          $value = htmlspecialchars($pagefile->{$name}, ENT_QUOTES, "UTF-8");
          $out[$basicField] .= "<label for='$for' data-group='{$basicField}' class='{$class}'>$label";
          $out[$basicField] .= "<textarea id='$for' name='$for' rows='3'>$value</textarea></label>";
        break;

        // link field. page list select
        case 'link':
          $value = (int)$pagefile->$name;
          $field = $this->modules->get('InputfieldPageListSelect');
          $field->startLabel = $this->_('Choose Link');
          $field->setAttribute('name+id', $for);
          $field->attr('value', $value);
          $out[$basicField] = $field->render();
        break;

        // other fields, input
        default:
          $class = 'InputfieldFileDescription input-imageextra infield';
          $value = htmlspecialchars($pagefile->{$name}, ENT_QUOTES, "UTF-8");
          $out[$basicField] = "<label for='$for' data-group='{$basicField}' class='{$class}'>$label";
          $out[$basicField] .= "<input type='text' name='$for' id='$for' value='$value' /></label>";
        break;

        // other fields multi-language, input
        case (preg_match('/([0-9])\w+/', $name) ? true : false):
          $class = 'InputfieldFileDescription input-imageextra__language infield';
          $value = htmlspecialchars($pagefile->{$name}, ENT_QUOTES, "UTF-8");
          $out[$basicField] .= "<label for='$for' data-group='{$basicField}' class='{$class}'>$label";
          $out[$basicField] .= "<input type='text' name='$for' id='$for' value='$value' /></label>";
        break;
      }
    }

    foreach ($out as $f => $o) {
      $out[$f] = "<div class='imageextra--wrapper'>{$o}</div>";
    }

    return implode('', $out);
  }

  /**
   * getLanguages - get other languages (id and title)
   *
   */
  public function getLanguages() {
    $languageIDs = array();
    $languageSupport = wire('modules')->get('LanguageSupport');
    foreach ($languageSupport->otherLanguagePageIDs as $languageID) {
      $language = $this->languages->get($languageID);
      $title = $language->title->getLanguageValue($language);
      if (empty($title)) {
        $title = $language->title->getLanguageValue($this->languages->get('default'));
      }

      $languageIDs[$languageID] = $title;
    }

    return $languageIDs;
  }

  /**
   * processInputFile - check changed values
   *
   * @param WireInputData $input
   * @param Pagefile $pagefile
   * @param int $n
   */
  protected function ___processInputFile(WireInputData $input, Pagefile $pagefile, $n) {
    $changed = parent::___processInputFile($input, $pagefile, $n);
    $id = $this->name . '_' . $pagefile->hash;

    foreach($this->customFields as $customField) {
      $name = $customField['name'];
      $type = $customField['type'];
      $for = $name . "_" . $id;
      $value = $input->$for;

      $value = ($type === 'textarea') ? $this->sanitizer->textarea($value) : $this->sanitizer->text($value);

      if ($pagefile->$name != $value) {
        $pagefile->set($name, $value);
        $changed = true;
      }
    }

    return $changed;
  }

}
